spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql4535

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:servlet:session:timeout: 30m	

#thymeleaf:
#prefix: classpath:/templates/
#suffix: .html
#mode: HTML
#cache: false
#
#logging:
#  level:
#    org.thymeleaf: DEBUG
spring:application:name: library
server:
  port: 8080
  servlet:
   context-path: /library