spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql4535
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      connection.useUnicode: true
      connection.characterEncoding: utf8mb4
      connection.charSet: utf8mb4
server:servlet:session:timeout: 30m	

#thymeleaf:
#prefix: classpath:/templates/
#suffix: .html
#mode: HTML
#cache: false
#
#logging:
#  level:
#    org.thymeleaf: DEBUG
spring:application:name: library
server:
  port: 8080
  servlet:
   context-path: /library